export const ActionConstants = {
  // Action input keys
  BASE_BRANCH_PATTERN_INPUT_KEY: 'BASE-BRANCH-PATTERN',
  PERSONAL_ACCESS_TOKEN_KEY: 'PERSONAL-ACCESS-TOKEN',
  RULES_LIMIT_INPUT_KEY: 'RULES-LIMIT',
  REQUIRED_NUMBER_OF_REVIEWERS: 'REQUIRED-NUMBER-OF-REVIEWERS',
  REQUIRED_STATUS_CHECKS: 'REQUIRED-STATUS-CHECKS',
  REQUIRE_REVIEW_FROM_CODEOWNERS: 'REQUIRE-REVIEW-FROM-CODEOWNERS',
  DISMISS_STALE_PR_APPROVALS_ON_NEW_COMMITS:
    'DISMISS-STALE-PR-APPROVALS-ON-NEW-COMMITS',
  REQUIRE_LINEAR_HISTORY: 'REQUIRE-LINEAR-HISTORY',
  ALLOW_FORCE_PUSHES: 'ALLOW-FORCE-PUSHES',
  ALLOW_DELETIONS: 'ALLOW-DELETIONS',
  INCLUDE_ADMINISTRATORS: 'INCLUDE-ADMINISTRATORS',
  RESTRICTION_USERS: 'RESTRICTION-USERS',
  RESTRICTION_TEAMS: 'RESTRICTION-TEAMS',
  RESTRICTION_APPS: 'RESTRICTION-APPS',

  // Event names
  CREATE_EVENT_NAME: 'create',
  DELETE_EVENT_NAME: 'delete',

  // Ref type
  BRANCH_REF_TYPE: 'branch',

  // Github GraphQL
  GRAPHQL_AUTH_TOKEN_PREFIX: 'token',
  GRAPHQL_MEDIATYPE_PREVIEWS: ['luke-cage']
}
